PROCESS BEFORE OUTPUT.
  MODULE set_status.
  MODULE set_sash.
  CALL SUBSCREEN subscreen1
       INCLUDING 'DEMO_DYNPRO_SPLITTER_CONTROL' '110'.
  CALL SUBSCREEN subscreen2
       INCLUDING 'DEMO_DYNPRO_SPLITTER_CONTROL' '120'.

PROCESS AFTER INPUT.
  MODULE cancel AT EXIT-COMMAND.
  MODULE get_sash.
  CALL SUBSCREEN subscreen1.
  CALL SUBSCREEN subscreen2.
